#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  5 23:56:26 2018

@author: thiagocrestani
"""

#ruim   
#5 menos provaveis + 10 mais provaveis 
a = 0     
for concurso in range(1696,1729):
    #concurso = 1702
    X_teste = []
    for i in range(concurso-1, concurso):
        X_teste.append(numeros_binario[i-quantidadeAmostrasAnteriores:i, 0:quantidadePrevisores])
    previsoes = regressor.predict(np.array(X_teste))
    #conferir
    res = list(previsoes.ravel())
    temp = []
    for i in range(0,2):
        temp.append(min(res))
        res.remove(min(res))   
    for i in range(0,10):
        res.remove(min(res))
    res = temp + res 
    apostas = []
    for i in range(0,25):
        if previsoes[0][i] in res:
            apostas.append(1)
        else:
            apostas.append(0) 
    acertos = 0
    #concurso = 1696
    for i in range(0,25):
        if apostas[i] == 1 and numeros_binario[concurso][i] == 1:
            acertos += 1
    vacertos[a].append(acertos)
    a += 1        
            
    #print acertos  
    
#ruim
a = 0     
for concurso in range(1696,1729):
    #concurso = 1702
    X_teste = []
    for i in range(concurso-1, concurso):
        X_teste.append(numeros_binario[i-quantidadeAmostrasAnteriores:i, 0:quantidadePrevisores])
    previsoes = regressor.predict(np.array(X_teste))
    #conferir
    res = list(previsoes.ravel())
    
    temp = []    
    temp.append(min(res))  
    res.remove(min(res))
    
    for i in range(0,6):        
        res.remove(min(res))
    
    temp = []    
    temp.append(min(res))  
    res.remove(min(res))
    
    temp.append(min(res))  
    res.remove(min(res))
    
    temp.append(min(res))  
    res.remove(min(res))
    
    temp.append(min(res))  
    res.remove(min(res))
    
    res.remove(min(res))
    res.remove(min(res))
    res.remove(min(res))
    res.remove(min(res))
    res.remove(min(res))
        
    res = temp + res 
    apostas = []
    for i in range(0,25):
        if previsoes[0][i] in res:
            apostas.append(1)
        else:
            apostas.append(0) 
    acertos = 0
    #concurso = 1696
    for i in range(0,25):
        if apostas[i] == 1 and numeros_binario[concurso][i] == 1:
            acertos += 1
    vacertos[a].append(acertos)
    a += 1 